name: Slack PR Notifier

on: pull_request

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Send GitHub Action trigger data to Slack via Message
        id: slack
        uses: slackapi/slack-github-action@v1.14.0
        with:
          payload: '{"text": "GitHub Actions Slack PR Notifier 메시지 도착했어요!!!!"}' # This data can be any valid JSON from a previous step in the GitHub Action
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
